version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # create multiple brokers
      KAFKA_ADVERTISED_HOST_NAME: <KAFKA_BROKER> #localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "<KAFKA_TOPICS>" #"topic:1:1,demo:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"